package main

// generated by "schematyper simple-schema-file-md5.json" -- DO NOT EDIT

type simpleSchemaFileMd5 struct {
	Fq1  string `json:"fq1"`
	Md5  string `json:"md5,omitempty"`
	Name string `json:"name"`
}
