# for fastq2PEbam and bams2cram
reference:  # type "File"
  class: File
  path: /home/ddbjshare-pg/jga-analysys/hg38/Homo_sapiens_assembly38.fasta
  format: http://edamontology.org/format_1929
# for fastqPE2bam
sortsam_max_records_in_ram: 5000000  # default value of type "int".
sortsam_java_options: -XX:-UseContainerSupport -Xmx30g  # default value of type "string".
bwa_num_threads: 16  # default value of type "int".
bwa_bases_per_batch: 10000000  # default value of type "int".
# for bams2cram
#sample_name: HG00174
bams2cram_reference:
  class: File
  path: "/home/ddbjshare-pg/jga-analysys/hg38/Homo_sapiens_assembly38.fasta"
  format: http://edamontology.org/format_1929
use_bqsr: false
dbsnp:
  class: File
  path: "/home/ddbjshare-pg/jga-analysys/hg38/Homo_sapiens_assembly38.dbsnp138.vcf"
  format: http://edamontology.org/format_3016
mills:
  class: File
  path: "/home/ddbjshare-pg/jga-analysys/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  format: http://edamontology.org/format_3016
known_indels:
  class: File
  path: "/home/ddbjshare-pg/jga-analysys/hg38/Homo_sapiens_assembly38.known_indels.vcf.gz"
  format: http://edamontology.org/format_3016
samtools_num_threads: 1
haplotypecaller_reference:
  class: File
  path: "/home/ddbjshare-pg/jga-analysys/hg38/Homo_sapiens_assembly38.fasta"
  format: http://edamontology.org/format_1929
gatk4_HaplotypeCaller_num_threads: 16
bgzip_num_threads: 16

sample_id: "HG00174"
runlist_pe: []
runlist_se:
  - run_id: ERR1025659 # type "string"
    fastq1:  # type "File"
      class: File
      path: /lustre8/home/hachiya-pg/jga-analysis-dev/test-03/small-fq/ERR1025659.small_1.fastq.gz
      format: http://edamontology.org/format_1930
    platform_name: ILLUMINA  # type "string"
  - run_id: ERR1025658 # type "string"
    fastq1:  # type "File"
      class: File
      path: /lustre8/home/hachiya-pg/jga-analysis-dev/test-03/small-fq/ERR1025659.small_2.fastq.gz
      format: http://edamontology.org/format_1930
    platform_name: ILLUMINA  # type "string"
  - run_id: ERR1419195 # type "string"
    fastq1:  # type "File"
      class: File
      path: /lustre8/home/hachiya-pg/jga-analysis-dev/test-03/small-fq/ERR1419195.small_1.fastq.gz
      format: http://edamontology.org/format_1930
    platform_name: ILLUMINA  # type "string"
  - run_id: ERR1419196 # type "string"
    fastq1:  # type "File"
      class: File
      path: /lustre8/home/hachiya-pg/jga-analysis-dev/test-03/small-fq/ERR1419195.small_2.fastq.gz
      format: http://edamontology.org/format_1930
    platform_name: ILLUMINA  # type "string"
                                                                      