name: Build and Publish Execute file

on:
  release:
    types:
      - published

jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - run: |
        mkdir -p dist
        env GOOS=linux  GOARCH=amd64 go build -o dist/jgaworkflowmanager-linux-$RELEASE_VERSION -ldflags "-X main.version=${RELEASE_VERSION} -X main.revision=$(git rev-parse --short HEAD)" main.go
        env GOOS=darwin GOARCH=amd64 go build -o dist/jgaworkflowmanager-mac-$RELEASE_VERSION -ldflags "-X main.version=${RELEASE_VERSION} -X main.revision=$(git rev-parse --short HEAD)" main.go
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/jgaworkflowmanager-*
