name: Build and Publish Execute file

on:
  release:
    types:
      - published

jobs:
  build_and_push:
    strategy:
      matrix:
        GOOS: ['linux', 'mac']
        GOARCH: ['amd64']
    runs-on: ubuntu-20.04
    env:
      GOOS: ${{ matrix.GOOS }}
      GOARCH: ${{ matrix.GOARCH }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - run: |
        mkdir -p dist
        go build -o dist/jgaworkflowmanager-$GOOS-$RELEASE_VERSION "-X main.version=${RELEASE_VERSION} -X main.revision=$(git rev-parse --short HEAD)" main.go
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/jgaworkflowmanager-*
